**1.- Carga de datos**

In [17]:
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt

df = pd.read_csv("../data/processed/route_cost_impact_limpio.csv")
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
print(df.head())

(3132, 23)
['month', 'conflict_phase', 'airline', 'iata_code', 'origin_city', 'destination_city', 'aircraft_type', 'original_distance_km', 'actual_distance_km', 'extra_distance_km', 'rerouted', 'flight_cancelled', 'fuel_consumption_bbl', 'brent_crude_usd', 'jet_fuel_usd_barrel', 'total_fuel_cost_usd', 'extra_fuel_cost_usd', 'base_ticket_price_usd', 'fuel_surcharge_usd', 'total_ticket_price_usd', 'estimated_passengers', 'route_revenue_usd', 'fuel_pct_of_cost']
month                         str
conflict_phase                str
airline                       str
iata_code                     str
origin_city                   str
destination_city              str
aircraft_type                 str
original_distance_km        int64
actual_distance_km        float64
extra_distance_km         float64
rerouted                      str
flight_cancelled              str
fuel_consumption_bbl      float64
brent_crude_usd           float64
jet_fuel_usd_barrel       float64
total_fuel_cost_usd       float64
extra_fuel_cost_usd       float64
base_ticket_price_usd     float64
fuel_surcharge_usd        float64
total_ticket_price_usd    float64
estimated_passengers        int64
route_revenue_usd         float64
fuel_pct_of_cost          float64
dtype: object
        month         conflict_phase   airline iata_code origin_city  \
0  2019-01-01  Pre-Pandemic Baseline  Emirates        EK       Dubai
1  2019-02-01  Pre-Pandemic Baseline  Emirates        EK       Dubai
2  2019-03-01  Pre-Pandemic Baseline  Emirates        EK       Dubai
3  2019-04-01  Pre-Pandemic Baseline  Emirates        EK       Dubai
4  2019-05-01  Pre-Pandemic Baseline  Emirates        EK       Dubai

  destination_city     aircraft_type  original_distance_km  \
0           London  Boeing 777-300ER                  5500
1           London  Boeing 777-300ER                  5500
2           London  Boeing 777-300ER                  5500
3           London  Boeing 777-300ER                  5500
4           London  Boeing 777-300ER                  5500

   actual_distance_km  extra_distance_km  ... brent_crude_usd  \
0              5500.0                0.0  ...           63.00
1              5500.0                0.0  ...           67.61
2              5500.0                0.0  ...           65.86
3              5500.0                0.0  ...           64.79
4              5500.0                0.0  ...           61.25

  jet_fuel_usd_barrel  total_fuel_cost_usd  extra_fuel_cost_usd  \
0               74.58               8949.6                  0.0
1               81.72               9806.4                  0.0
2               76.87               9224.4                  0.0
3               73.34               8800.8                  0.0
4               72.97               8756.4                  0.0

   base_ticket_price_usd  fuel_surcharge_usd  total_ticket_price_usd  \
0                 361.93               77.12                  439.05
1                 396.58               92.60                  489.18
2                 373.05               81.93                  454.98
3                 355.91               74.58                  430.49
4                 354.12               73.83                  427.95

   estimated_passengers  route_revenue_usd  fuel_pct_of_cost
0                   231          101420.55             97.02
1                   259          126697.62             97.27
2                   220          100095.60             97.11
3                   263          113218.87             96.97
4                   283          121109.85             96.96

[5 rows x 23 columns]

**2.-Revisión de estructura**

Se analiza la estructura del dataset para comprender la distribución
de variables, tipos de datos y posibles valores atípicos o inconsistencias.

In [9]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3132 entries, 0 to 3131
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   month                   3132 non-null   str
 1   conflict_phase          3132 non-null   str
 2   airline                 3132 non-null   str
 3   iata_code               3132 non-null   str
 4   origin_city             3132 non-null   str
 5   destination_city        3132 non-null   str
 6   aircraft_type           3132 non-null   str
 7   original_distance_km    3132 non-null   int64
 8   actual_distance_km      3132 non-null   float64
 9   extra_distance_km       3132 non-null   float64
 10  rerouted                3132 non-null   str
 11  flight_cancelled        3132 non-null   str
 12  fuel_consumption_bbl    3132 non-null   float64
 13  brent_crude_usd         3132 non-null   float64
 14  jet_fuel_usd_barrel     3132 non-null   float64
 15  total_fuel_cost_usd     3132 non-null   float64
 16  extra_fuel_cost_usd     3132 non-null   float64
 17  base_ticket_price_usd   3132 non-null   float64
 18  fuel_surcharge_usd      3132 non-null   float64
 19  total_ticket_price_usd  3132 non-null   float64
 20  estimated_passengers    3132 non-null   int64
 21  route_revenue_usd       3132 non-null   float64
 22  fuel_pct_of_cost        3132 non-null   float64
dtypes: float64(12), int64(2), str(9)
memory usage: 562.9 KB

,original_distance_km,actual_distance_km,extra_distance_km,fuel_consumption_bbl,brent_crude_usd,jet_fuel_usd_barrel,total_fuel_cost_usd,extra_fuel_cost_usd,base_ticket_price_usd,fuel_surcharge_usd,total_ticket_price_usd,estimated_passengers,route_revenue_usd,fuel_pct_of_cost
count,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000,3132.000000
mean,6039.611111,6078.737229,39.126117,127.033525,80.184368,93.624138,11952.704879,157.676213,498.929374,143.715801,642.645176,241.433908,152580.331651,97.259962
std,3002.592295,3033.226488,218.954889,56.761229,24.362462,28.374818,6899.205816,891.745391,300.065824,114.206751,409.861986,42.028976,101081.087401,1.344451
min,1248.000000,1248.000000,0.000000,35.000000,20.550000,23.690000,829.150000,0.000000,26.090000,1.770000,27.860000,0.000000,0.000000,89.920000
25%,4320.500000,4519.500000,0.000000,102.150000,66.500000,76.870000,6746.255000,0.000000,259.995000,65.797500,330.652500,226.000000,75378.355000,97.090000
50%,5376.500000,5418.000000,0.000000,115.000000,82.610000,94.920000,10861.190000,0.000000,448.250000,119.250000,564.875000,246.000000,136080.545000,97.600000
75%,7975.250000,8000.000000,0.000000,165.000000,91.480000,109.200000,15532.340000,0.000000,665.840000,188.247500,852.917500,266.000000,202737.262500,97.920000
max,12003.000000,14131.000000,2345.000000,282.500000,169.080000,193.200000,54579.000000,10796.970000,2046.160000,920.770000,2966.930000,284.000000,750646.560000,99.100000

**3.- Variables derivadas**

Se generan nuevas variables a partir de las columnas originales con el fin de capturar de mejor manera el impacto operacional y económico de las rutas aéreas.

Estas transformaciones facilitan el análisis posterior, especialmente para comparar fases del conflicto, desvíos, costos e ingresos.

In [19]:
# Se crea una variable `route` que combina ciudad de origen y destino 
# para facilitar agrupaciones y comparaciones por trayecto.
df["route"] = df["origin_city"] + " → " + df["destination_city"]

df[["origin_city", "destination_city", "route"]].head()

  origin_city destination_city           route
0       Dubai           London  Dubai → London
1       Dubai           London  Dubai → London
2       Dubai           London  Dubai → London
3       Dubai           London  Dubai → London
4       Dubai           London  Dubai → London

**4.-Agregaciones**

**5.-Joins y comparaciones contra baseline**

**6.-Tablas pivote y reshape**

**7.-Visualizaciones**

**8.-Hallazgos**

**9.-Resumen para presentación**